### ISSUE TITLE
Compatibility with Stream deck XL ?

### ISSUE THREAD

**Issue by PicreSenar** [mysnphit/ElgatoLeagueTracker#2]
Nice plugin !
Have you tried the compatibility with a Stream deck XL ?
Do I have to know some specific tricks to make it work with it ?

Other question, Is it mandatory that you use a specific profile ?
Can't we simply use a file to put them in ? (only possible with an XL as 15 buttons are used)

Thanks

**Comment by pwnyprod** [comment]
its compatible, i used it there. can be closed.

**Comment by mysnphit** [comment]
Thank you for testing it :smiley:
